on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt

      - name: Build fSkripta
        run: |
          TZ=UTC make html #fixing ValueError: ZoneInfo keys may not be absolute paths, got: /UTC

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit Changes To Github Pages
        run: |
          git checkout gh-pages
          git clone https://github.com/fSkripta/fskripta.github.io.git --branch gh-pages --single-branch gh-pages
          cd gh-pages
          chmod +x make
          TZ=UTC ./make
          git add docs/*
          git commit -m "Update webpage." || true  # Allow commit if there are no changes
      - name: Commit Changes To Github Pages
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
